apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  selector:
    matchLabels:
      app: k8s-test
  replicas: 2 
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
        - name: k8s-test
          image: enzopcastillo/devops-test 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090 # The port that the container is running on in the cluster

---

apiVersion: v1 
kind: Service
metadata: 
  name: k8s-svc
spec:
  selector:
    app: k8s-test
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8090 # The port exposed by the service
  type: NodePort