apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-nginx
  template:
    metadata:
      labels:
        app: k8s-nginx
    spec:
      containers:
      - name: k8s-nginx
        image: docker/getting-started:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-nginx-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-nginx
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001